=== samantha-pogue/bonspiel-data/structure.dtd
<!ELEMENT bonspiel (location, member, game+, event+, wins, losses, merit_points)>
<!ATTLIST bonspiel season (2019-2020|2020-2021) #REQUIRED>
<!ELEMENT location (#PCDATA)>
<!ELEMENT member (#PCDATA)>
<!ELEMENT game (game_outcome)>
<!ATTLIST game against (UWSP|Nebraska|UWGB|StNorbert|WayneState) #REQUIRED>
<!ELEMENT game_outcome (#PCDATA)>
<!ELEMENT event (event_outcome)>
<!ATTLIST event placement (first|second|third|fourth) #REQUIRED>
<!ATTLIST event opponent (UWSP|Nebraska|UWGB|StNorbert|WayneState) #REQUIRED>
<!ELEMENT event_outcome (#PCDATA)>
<!ELEMENT wins (#PCDATA)>
<!ELEMENT losses (#PCDATA)>
<!ELEMENT merit_points (#PCDATA)>

=== samantha-pogue/bonspiel-data/bonspiels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bonspiel SYSTEM "structure.dtd">


  <bonspiel season="2019-2020">
    <location>University of Wisconsin-Stevens Point</location>
    <member>Callie Wesenick</member>
    <member>Joshua Proehl</member>
    <member>Alex Duhaime</member>
    <!--first match-->
    <game against="UWSP">
      <game_outcome>win</game_outcome>
    </game>
    <!--second match-->
    <game against="Nebraska">
      <game_outcome>loss</game_outcome>
    </game>
    <!--third match-->
    <game against="StNorbert">
      <game_outcome>win</game_outcome>
    </game>
    <!--event-->
    <event placement="second" opponent="UWSP">
      <event_outcome>win</event_outcome>
    </event>
    <wins>2</wins>
    <losses>1</losses>
    <merit_points>2</merit_points>
  </bonspiel>

  <bonspiel season="2019-2020">
    <location>Rice Lake</location>
    <member>Callie Wesenick</member>
    <member>Joshua Proehl</member>
    <member>Alex Duhaime</member>
    <member>Joshua Schellpfeffer</member>
    <!--first match-->
    <game against="UWSP">
      <game_outcome>win</game_outcome>
    </game>
    <!--second match-->
    <game against="Nebraska">
      <game_outcome>loss</game_outcome>
    </game>
    <!--third match-->
    <game against="StNorbert">
      <game_outcome>win</game_outcome>
    </game>
    <!--event-->
    <event placement="second" opponent="UWSP">
      <event_outcome>win</event_outcome>
    </event>
    <wins>2</wins>
    <losses>1</losses>
    <merit_points>2</merit_points>
  </bonspiel>
